# Application {#application}

Once the PTI dashboard is launched, you can use it to construct a composite weighted index. You first need to select a set of indicators that should be used to construct a PTI. The PTI is a composite index of several development indicators chosen to inform geographical targeting. Often, some indicators vary significantly across a country. One example is the number of poor people living in each district. If such an indicator is combined with other indicators with limited variation, the composite PTI indicator tends to heavily reflect the geographic pattern of the poor population. To avoid this, the PTI standardizes all indicators to have mean and variance of 0 and 1 respectively. These standardized indicators are then combined into a composite index. The PTI aggregates the standardized indicators with weights, which reflect the relative importance of each variable. As the weight of an indicator increases, the geographic distribution of priority areas of PTI is more affected by that indicator. More formally, the PTI can be expressed as follows:

$$\begin{array}{ccc}
PTI = \Sigma_{i=1}^{n} z_i \times w_i
\end{array}$$ 
where $z_i$ is the z-score of indicator $i$ used to compute the PTI and $w_i$ is the weight assigned to each indicator. 

To facilitate the process of choosing which weights to assign to different indicators, the PTI dashboard can be used to test different variants of the PTI using a different permutation of indicators and weights and evaluate how priority areas may change under different assumptions. 
